### ISSUE TITLE
"kettle over kettleTransFromFile" in BI Server not processing variable names in "Set session variables" correcly

### ISSUE THREAD

**Issue by ChrisMolanus** [webdetails/kettle-baserver-utils#4]
`<step>
    <name>Set session variables</name>
    <type>SetSessionVariableStep</type>
    <description/>
    <distribute>N</distribute>
    <custom_distribution/>
    <copies>1</copies>
         <partitioning>
           <method>none</method>
           <schema_name/>
           </partitioning>
    <fields>
      <field>
        <name>constaint</name>
        <variable>constaint</variable>
        <default_value>&#x22;test&#x22;</default_value>
        </field>
      <field>
        <name>client_name</name>
        <variable>client_name</variable>
        <default_value>&#x24;&#x7b;username&#x7d;</default_value>
        </field>
      </fields>
    <use_formatting>N</use_formatting>
     <cluster_schema/>
 <remotesteps>   <input>   </input>   <output>   </output> </remotesteps>    <GUI>
      <xloc>458</xloc>
      <yloc>86</yloc>
      <draw>Y</draw>
      </GUI>
    </step>`

org.pentaho.di.core.exception.KettleException: 
There was no variable name specified for value [dim_country_id = "Netherlands1"]

at pt.webdetails.di.baserver.utils.SetSessionVariableStep.setValue(SetSessionVariableStep.java:98) 
at pt.webdetails.di.baserver.utils.SetSessionVariableStep.processRow(SetSessionVariableStep.java:62) 
at org.pentaho.di.trans.step.RunThread.run(RunThread.java:62) 
at java.lang.Thread.run(Unknown Source) 
2015/01/12 15:12:08 - Set session variables.0 - ERROR (version 5.2.1.0-148, build 1 from 2014-12-08_14-49-19 by buildguy) : Unexpected error 
2015/01/12 15:12:08 - Table input.0 - Finished processing (I=1, O=0, R=0, W=1, U=0, E=0) 
2015/01/12 15:12:08 - Set session variables.0 - ERROR (version 5.2.1.0-148, build 1 from 2014-12-08_14-49-19 by buildguy) : org.pentaho.di.core.exception.KettleException: 
2015/01/12 15:12:08 - Set session variables.0 - There was no variable name specified for value [dim_country_id = "Netherlands1"] 
2015/01/12 15:12:08 - Set session variables.0 - 
2015/01/12 15:12:08 - Set session variables.0 - at pt.webdetails.di.baserver.utils.SetSessionVariableStep.setValue(SetSessionVariableStep.java:98) 
2015/01/12 15:12:08 - Set session variables.0 - at pt.webdetails.di.baserver.utils.SetSessionVariableStep.processRow(SetSessionVariableStep.java:62) 
2015/01/12 15:12:08 - Set session variables.0 - at org.pentaho.di.trans.step.RunThread.run(RunThread.java:62) 
2015/01/12 15:12:08 - Set session variables.0 - at java.lang.Thread.run(Unknown Source)

BAServerUtils v0.2
BA Serer: 5.2.1.0

OS: 
Distributor ID: Ubuntu 
Description: Ubuntu 14.04.1 LTS 
Release: 14.04 
Codename: trusty

Java:(packaged with BA Server) 
java version "1.7.0_60" 
Java(TM) SE Runtime Environment (build 1.7.0_60-b19) 
Java HotSpot(TM) 64-Bit Server VM (build 24.60-b09, mixed mode)

**Comment by ChrisMolanus** [comment]
Found it:

In webdetails/kettle-baserver-utils, "kettle-baserver-utils/src/pt/webdetails/di/baserver/utils/SetSessionVariableMeta.java" 8708c1ff3380d932dd0ea158a27d6fb91a194601.

The functions readRep and saveRep
use different labels for  storing and retrieving the "field variable", namely "field_variable" and "field_variable_name"   . This bug would only be notices if this step was run using a KTR stored in a repository.


On line 177"
        variableName[ i ] = rep.getStepAttributeString( id_step, i, "field_variable" );

On line 193
rep.saveStepAttribute( id_transformation, id_step, i, "field_variable_name", variableName[ i ] );
