### ISSUE TITLE
SetSessionVariableStep.java

### ISSUE THREAD

**Issue by ChrisMolanus** [webdetails/kettle-baserver-utils#5]
`<step>
    <name>Set session variables</name>
    <type>SetSessionVariableStep</type>
    <description/>
    <distribute>N</distribute>
    <custom_distribution/>
    <copies>1</copies>
         <partitioning>
           <method>none</method>
           <schema_name/>
           </partitioning>
    <fields>
      <field>
        <name>constaint</name>
        <variable>constaint</variable>
        <default_value>&#x22;test&#x22;</default_value>
        </field>
      <field>
        <name>client_name</name>
        <variable>client_name</variable>
        <default_value>&#x24;&#x7b;username&#x7d;</default_value>
        </field>
      </fields>
    <use_formatting>N</use_formatting>
     <cluster_schema/>
 <remotesteps>   <input>   </input>   <output>   </output> </remotesteps>    <GUI>
      <xloc>458</xloc>
      <yloc>86</yloc>
      <draw>Y</draw>
      </GUI>
    </step>`

org.pentaho.di.core.exception.KettleException: 
There was no variable name specified for value [dim_country_id = "Netherlands1"]

at pt.webdetails.di.baserver.utils.SetSessionVariableStep.setValue(SetSessionVariableStep.java:98) 
at pt.webdetails.di.baserver.utils.SetSessionVariableStep.processRow(SetSessionVariableStep.java:62) 
at org.pentaho.di.trans.step.RunThread.run(RunThread.java:62) 
at java.lang.Thread.run(Unknown Source) 
2015/01/12 15:12:08 - Set session variables.0 - ERROR (version 5.2.1.0-148, build 1 from 2014-12-08_14-49-19 by buildguy) : Unexpected error 
2015/01/12 15:12:08 - Table input.0 - Finished processing (I=1, O=0, R=0, W=1, U=0, E=0) 
2015/01/12 15:12:08 - Set session variables.0 - ERROR (version 5.2.1.0-148, build 1 from 2014-12-08_14-49-19 by buildguy) : org.pentaho.di.core.exception.KettleException: 
2015/01/12 15:12:08 - Set session variables.0 - There was no variable name specified for value [dim_country_id = "Netherlands1"] 
2015/01/12 15:12:08 - Set session variables.0 - 
2015/01/12 15:12:08 - Set session variables.0 - at pt.webdetails.di.baserver.utils.SetSessionVariableStep.setValue(SetSessionVariableStep.java:98) 
2015/01/12 15:12:08 - Set session variables.0 - at pt.webdetails.di.baserver.utils.SetSessionVariableStep.processRow(SetSessionVariableStep.java:62) 
2015/01/12 15:12:08 - Set session variables.0 - at org.pentaho.di.trans.step.RunThread.run(RunThread.java:62) 
2015/01/12 15:12:08 - Set session variables.0 - at java.lang.Thread.run(Unknown Source)

BAServerUtils v0.2
BA Serer: 5.2.1.0

OS: 
Distributor ID: Ubuntu 
Description: Ubuntu 14.04.1 LTS 
Release: 14.04 
Codename: trusty

Java:(packaged with BA Server) 
java version "1.7.0_60" 
Java(TM) SE Runtime Environment (build 1.7.0_60-b19) 
Java HotSpot(TM) 64-Bit Server VM (build 24.60-b09, mixed mode)

**Comment by marcovala** [comment]
Usually that exception is raised when you didn't specify a name for the session variable. 
Is the column "Variable name" in the "Set Session Variables" step empty?

**Comment by ChrisMolanus** [comment]
This is the bug I emailed you.







Marco Vala
11:47 (1 hour ago)
to me, Bram, Julien, Timo
Hi Chris,

That is indeed a bug!

I will fix it asap, but it should take a few days before we do a new
release of the BA Server Utils that includes the fix.

Thanks for reporting.

Best regards,



Chris Molanus
Consultant business intelligence

*e: * chris.molanus@incentro.com
 *t: * +31157640750
 *m: * +31624528415
 *w: *  www.incentro.com

nootdorp office
gildeweg 5b  |  2632 bd   |  nootdorp

[image: incentro] <http://www.incentro.com>

[image: incentro news] <http://short.incentro.com/newsbanner>

On 13 January 2015 at 11:38, Marco Vala <notifications@github.com> wrote:

> Usually that exception is raised when you didn't specify a name for the
> session variable.
> Is the column "Variable name" in the "Set Session Variables" step empty?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/webdetails/kettle-baserver-utils/issues/5#issuecomment-69725497>
> .
>


Chris Molanus
Consultant business intelligence

*e: * chris.molanus@incentro.com
 *t: * +31157640750
 *m: * +31624528415
 *w: *  www.incentro.com

nootdorp office
gildeweg 5b  |  2632 bd   |  nootdorp

[image: incentro] <http://www.incentro.com>

[image: incentro news] <http://short.incentro.com/newsbanner>
